<a href="https://colab.research.google.com/github/kunalkawadkar/data_encoding/blob/main/DataEncoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# change into categorical data to numerical data

# Nominal / one encoding

In [ ]:
import pandas as pd

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
# create a sample datafream with categorical feature

df =pd.DataFrame({'colour':['blue','green','red','red','blue','green']})

In [ ]:
df

colour
0   blue
1  green
2    red
3    red
4   blue
5  green

In [ ]:
## create an instance one hot encoder


encoder = OneHotEncoder()








In [ ]:
encoder.fit_transform(df[['colour']])  # created sparse matix

<6x3 sparse matrix of type '<class 'numpy.float64'>'
	with 6 stored elements in Compressed Sparse Row format>

In [ ]:
encoder.fit_transform(df[['colour']]).toarray() # created sparse matix


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [ ]:
encoded = encoder.fit_transform(df[['colour']])

In [ ]:
import pandas as pd

In [ ]:
encoded_df =pd.DataFrame(encoded.toarray(),columns=encoder.get_feature_names_out())

In [ ]:
pd.concat([df,encoded_df],axis=1)

colour  colour_blue  colour_green  colour_red
0   blue          1.0           0.0         0.0
1  green          0.0           1.0         0.0
2    red          0.0           0.0         1.0
3    red          0.0           0.0         1.0
4   blue          1.0           0.0         0.0
5  green          0.0           1.0         0.0

# Label and ordinal encoding

In [ ]:
import pandas as pd

In [ ]:
from sklearn.preprocessing import  LabelEncoder

In [ ]:
# create a sample datafream with categorical feature

df =pd.DataFrame({'colour':['blue','green','red','red','blue','green']})

In [ ]:
df

colour
0   blue
1  green
2    red
3    red
4   blue
5  green

In [ ]:
encoder1 =LabelEncoder()

In [ ]:
encoder1.fit_transform(df['colour'])

array([0, 1, 2, 2, 0, 1])

In [ ]:
## ordinal encoding
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder


In [ ]:
# create a sample dataset of ordinal variables
df1= pd.DataFrame({'size':['small','medium', 'large','medium','large','small']})

In [ ]:
df1

size
0   small
1  medium
2   large
3  medium
4   large
5   small

In [ ]:
# create a instance of the ordinalencoder class and fit_transform
encoder=OrdinalEncoder(categories=[['small','medium','large']])

In [ ]:
encoder.fit_transform(df1[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [2.],
       [0.]])

#Target Guided Ordinal Encoding
It is a technique used to encode categorical variables based on their relationship with the target variable. This encoding technique is useful when we have a categorical variable with a large number of unique categories, and we want to use this variable as a feature in our machine learning model.

In Target Guided Ordinal Encoding, we replace each category in the categorical variable with a numerical value based on the mean or median of the target variable for that category. This creates a monotonic relationship between the categorical variable and the target variable, which can improve the predictive power of our model.

In [ ]:
import pandas as pd

# create a sample dataframe with a categorical variable and a target variable
df = pd.DataFrame({
    'city': ['New York', 'London', 'Paris', 'Tokyo', 'New York', 'Paris'],
    'price': [200, 150, 300, 250, 180, 320]
})

In [ ]:
df


city  price
0  New York    200
1    London    150
2     Paris    300
3     Tokyo    250
4  New York    180
5     Paris    320

In [ ]:
## calculate the mean price for each city
mean_price=df.groupby('city')['price'].mean().to_dict()
mean_price

{'London': 150.0, 'New York': 190.0, 'Paris': 310.0, 'Tokyo': 250.0}

In [ ]:
## replace each city with its mean price
df['city_encoded']=df['city'].map(mean_price)

In [ ]:
df


city  price  city_encoded
0  New York    200         190.0
1    London    150         150.0
2     Paris    300         310.0
3     Tokyo    250         250.0
4  New York    180         190.0
5     Paris    320         310.0